#!/usr/bin/env python
"""08b_discordance_recordlevel.py — record-level reconstruction of the
carbapenemase genotype-phenotype discordance analysis.

WHY THIS SCRIPT REPLACES 08_discordance_analysis.py
---------------------------------------------------
The earlier script aggregated all MIC records for a genome (median value,
logical OR of censoring flags) BEFORE applying the testing-method and
interpretive-standard restrictions, and retained an arbitrary metadata row per
genome. Two consequences:

  (a) a genome assigned to the "CLSI broth microdilution" stratum could carry a
      median MIC computed partly from records generated by other methods,
      standards or laboratories; the stratum was therefore not a record-level
      stratum;
  (b) taking the median value together with the maximum of the left- and
      right-censoring indicators could construct an interval supported by no
      original record (e.g. <=1, 4 and >=8 collapsing to "4, both censored").

This script instead:
  1. keeps one row per PHENOTYPE RECORD with its method, standard, platform,
     year and censoring attached;
  2. applies stratification restrictions AT RECORD LEVEL;
  3. resolves multiple surviving records per genome by INTERVAL INTERSECTION
     under an explicit evidence hierarchy;
  4. flags genomes whose records are mutually contradictory and excludes them
     from the primary analysis, reporting them separately.

Usage:
    python scripts/08b_discordance_recordlevel.py                      # unrestricted
    python scripts/08b_discordance_recordlevel.py --standard CLSI \
        --method "Broth dilution" --tag _clsi_bmd                      # primary
    python scripts/08b_discordance_recordlevel.py --breakpoints EUCAST --tag _eucast
"""
import argparse
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

sys.path.insert(0, str(Path(__file__).parent))
from kp_defs import (PORIN_LABEL, PORIN_ORDER, available_drugs, carb_allele,
                     carb_family, get_breakpoints, has_carb,
                     porin_disrupted, porin_status)

RAW_PHEN = Path("data/raw/phenotypes/kp_amr_anchor.tsv")
KLEB = Path("data/processed/kleborate_klebsiella_pneumo_complex_output.tsv")
OUTDIR = Path("results/tables")

C_STRAIN = "strain"
C_SPECIES = "enterobacterales__species__species"
C_ST = "klebsiella_pneumo_complex__mlst__ST"
C_CARB = "klebsiella_pneumo_complex__amr__Bla_Carb_acquired"
C_OMP = "klebsiella_pneumo_complex__amr__Omp_mutations"
C_ESBL = "klebsiella_pneumo_complex__amr__Bla_ESBL_acquired"

# evidence hierarchy for resolving multiple records (lower rank = preferred)
METHOD_RANK = {"broth dilution": 0, "mic": 1, "agar dilution": 2,
               "disk diffusion": 9, "": 5}


def wilson(k, n):
    if n == 0:
        return (np.nan, np.nan, np.nan)
    p = k / n; z = 1.959964
    d = 1 + z**2 / n
    c = (p + z**2 / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z**2 / (4 * n**2)) / d
    return (100 * p, 100 * max(0, c - h), 100 * min(1, c + h))


# ---------------------------------------------------------------- intervals
def record_interval(value, sign):
    """Interval of possible true MICs, WITH bound inclusivity.

    Returns (lo, hi, lo_inc, hi_inc). Inclusivity matters: a record of '>8'
    describes (8, inf) — OPEN at 8 — so every possible value is strictly
    greater than 8 and the record IS resistant under a 'R > 8' breakpoint.
    Storing only the numeric bound and testing 8 > 8 wrongly returns
    "ambiguous", discarding most right-censored records under EUCAST.
    """
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return None
    s = (sign or "").strip()
    v = float(value)
    if s == "<=":
        return (0.0, v, False, True)      # (0, v]
    if s == "<":
        return (0.0, v, False, False)     # (0, v)
    if s == ">=":
        return (v, math.inf, True, False)  # [v, inf)
    if s == ">":
        return (v, math.inf, False, False)  # (v, inf)
    return (v, v, True, True)             # {v}


def intersect(a, b):
    """Intersection of two intervals, preserving bound inclusivity."""
    if a[0] > b[0]:
        lo, lo_inc = a[0], a[2]
    elif b[0] > a[0]:
        lo, lo_inc = b[0], b[2]
    else:
        lo, lo_inc = a[0], (a[2] and b[2])
    if a[1] < b[1]:
        hi, hi_inc = a[1], a[3]
    elif b[1] < a[1]:
        hi, hi_inc = b[1], b[3]
    else:
        hi, hi_inc = a[1], (a[3] and b[3])
    if lo > hi:
        return None
    if lo == hi and not (lo_inc and hi_inc):
        return None
    return (lo, hi, lo_inc, hi_inc)


def classify_interval(iv, bp_s, bp_r, s_op="<=", r_op=">="):
    """S/I/R only when EVERY value in the interval satisfies one category.

    Bound inclusivity is essential. '>8' is (8, inf): every value is strictly
    above 8, so under 'R > 8' the record is resistant even though the stored
    lower bound equals 8.
    """
    if iv is None:
        return "ambiguous"
    lo, hi, lo_inc, hi_inc = iv

    def all_susceptible():
        # every value <= bp_s (or < bp_s)
        if s_op == "<=":
            return hi < bp_s or (hi == bp_s and True)
        return hi < bp_s or (hi == bp_s and not hi_inc)

    def all_resistant():
        if r_op == ">=":
            return lo > bp_r or (lo == bp_r and True)
        return lo > bp_r or (lo == bp_r and not lo_inc)

    def all_intermediate():
        # strictly between the breakpoints: not susceptible at the low end,
        # not resistant at the high end
        low_ok = lo > bp_s or (lo == bp_s and not lo_inc)
        high_ok = hi < bp_r or (hi == bp_r and (True if r_op == ">" else not hi_inc))
        return low_ok and high_ok

    if all_susceptible():
        return "S"
    if all_resistant():
        return "R"
    if all_intermediate():
        return "I"
    return "ambiguous"


# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--drug", default="meropenem")
    ap.add_argument("--standard", default=None, help="e.g. CLSI")
    ap.add_argument("--method", default=None, help="e.g. 'Broth dilution'")
    ap.add_argument("--breakpoints", default="CLSI",
                    help="interpretive standard, e.g. CLSI or EUCAST")
    ap.add_argument("--dedup", action="store_true")
    ap.add_argument("--collapse-porin", action="store_true",
                    help="use the coarser porin scheme of earlier analyses")
    ap.add_argument("--min-n", type=int, default=10)
    ap.add_argument("--tag", default="")
    a = ap.parse_args()

    bp = get_breakpoints(a.drug, a.breakpoints)   # refuses if unverified
    OUTDIR.mkdir(parents=True, exist_ok=True)
    if not RAW_PHEN.exists():
        sys.exit(f"ERROR: {RAW_PHEN} not found")
    if not KLEB.exists():
        sys.exit(f"ERROR: {KLEB} not found")

    # ---------- 1. RECORD-LEVEL phenotype table ----------
    raw = pd.read_csv(RAW_PHEN, sep="\t", dtype=str, low_memory=False).fillna("")
    cols = {c.lower().strip(): c for c in raw.columns}
    gid = cols.get("genome_id"); abx = cols.get("antibiotic")
    val = cols.get("measurement_value"); sgn = cols.get("measurement_sign")
    unit = cols.get("measurement_unit"); meth = cols.get("laboratory_typing_method")
    std = cols.get("testing_standard"); plat = cols.get("laboratory_typing_platform")
    yr = cols.get("testing_standard_year")
    if not (gid and abx and val):
        sys.exit("ERROR: required columns not found in the raw phenotype table")

    r = raw[raw[abx].str.lower().str.strip() == a.drug.lower()].copy()
    n_all = len(r)
    r["genome_id"] = r[gid].astype(str).str.strip()
    r["method"] = r[meth].str.strip() if meth else ""
    r["standard"] = r[std].str.strip() if std else ""
    r["platform"] = r[plat].str.strip() if plat else ""
    r["year"] = r[yr].str.strip() if yr else ""
    r["sign"] = r[sgn].str.strip() if sgn else ""
    r["value"] = pd.to_numeric(r[val].str.strip(), errors="coerce")

    print("=" * 78)
    print(f"RECORD-LEVEL DISCORDANCE ANALYSIS — {a.drug.upper()}")
    print(f"breakpoints: {a.breakpoints} "
          f"(S {bp.get('S_op','<=')} {bp['S']}, R {bp.get('R_op','>=')} {bp['R']} mg/L)"
          f"  [{bp['source']}]")
    print("=" * 78)
    print(f"phenotype records for {a.drug}: {n_all:,}")

    # exclude non-MIC units at RECORD level
    if unit:
        bad = r[unit].str.strip().str.lower().isin({"mm"})
        if bad.any():
            print(f"  excluded {int(bad.sum())} disk-diffusion (mm) records")
            r = r[~bad]
    # exclude computationally predicted phenotypes at RECORD level
    if meth:
        comp = r["method"].str.contains("computational", case=False, na=False)
        if comp.any():
            print(f"  excluded {int(comp.sum())} computationally predicted records")
            r = r[~comp]
    r = r.dropna(subset=["value"])
    r0 = r.copy()                     # after unit/computational/numeric filters
    print(f"  records with a numeric value: {len(r):,}")

    # ---------- 2. stratification AT RECORD LEVEL ----------
    n_after_std = len(r)
    if a.standard:
        before = len(r)
        r = r[r["standard"].str.upper() == a.standard.upper()]
        n_after_std = len(r)
        print(f"  standard == {a.standard}: {before:,} -> {len(r):,} records")
    if a.method:
        before = len(r)
        r = r[r["method"].str.lower() == a.method.strip().lower()]
        print(f"  method == '{a.method}': {before:,} -> {len(r):,} records")
    if len(r) == 0:
        sys.exit("no records survive the stratification filters")

    r["interval"] = [record_interval(v, s) for v, s in zip(r["value"], r["sign"])]
    r = r[r["interval"].notna()]
    r["_rank"] = r["method"].str.lower().map(METHOD_RANK).fillna(5)

    # ---------- 3. resolve multiple records per genome by INTERSECTION ----------
    resolved, conflicts = [], []
    for g, grp in r.groupby("genome_id", sort=False):
        grp = grp.sort_values("_rank", kind="stable")
        ivs = list(grp["interval"])
        cur = ivs[0]
        ok = True
        for iv in ivs[1:]:
            nxt = intersect(cur, iv)
            if nxt is None:
                ok = False
                break
            cur = nxt
        rec = dict(genome_id=g, n_records=len(grp),
                   lo=cur[0], hi=cur[1], lo_inc=cur[2], hi_inc=cur[3],
                   method=grp["method"].iloc[0], standard=grp["standard"].iloc[0],
                   platform=grp["platform"].iloc[0], year=grp["year"].iloc[0])
        (resolved if ok else conflicts).append(rec)

    ph = pd.DataFrame(resolved)
    cf = pd.DataFrame(conflicts)
    n_genomes_with_record = len(ph) + len(cf)
    print(f"\n  genomes with >=1 usable record : {n_genomes_with_record:,}")
    print(f"    resolved by interval intersection : {len(ph):,}")
    print(f"    CONTRADICTORY records (excluded)  : {len(cf):,}")
    if len(cf):
        print("      -> reported separately; these genomes have records whose")
        print("         intervals do not overlap and cannot be reconciled.")

    # ---------- 4. genotypes ----------
    kb = pd.read_csv(KLEB, sep="\t", dtype=str, low_memory=False)
    n_kb = len(kb)
    kb = kb[kb[C_SPECIES].astype(str).str.contains("pneumoniae", case=False, na=False)]
    n_kb_kp = len(kb)
    print(f"\n  Kleborate genomes: {n_kb:,} -> {len(kb):,} confirmed K. pneumoniae")
    kb["genome_id"] = kb[C_STRAIN].astype(str).str.strip()
    kb["carb_pos"] = kb[C_CARB].apply(has_carb)
    kb["carb_family"] = kb[C_CARB].apply(carb_family)
    kb["carb_allele"] = kb[C_CARB].apply(carb_allele)
    kb["porin"] = kb[C_OMP].apply(lambda v: porin_status(v, collapse=a.collapse_porin))
    kb["porin_disrupted"] = kb["porin"].apply(porin_disrupted)
    kb["esbl"] = kb[C_ESBL].apply(has_carb) if C_ESBL in kb.columns else False
    kb["ST"] = kb[C_ST].astype(str)

    d = kb.merge(ph, on="genome_id", how="inner")
    print(f"  joined genotype + phenotype: {len(d):,} genomes")

    if a.dedup:
        before = len(d)
        d = d.drop_duplicates(subset=["ST", "carb_allele", "porin"])
        print(f"  deduplicated (ST x allele x porin): {before:,} -> {len(d):,}")

    # ---------- 5. classification ----------
    d["call"] = [classify_interval((lo, hi, li, hi_i), bp["S"], bp["R"],
                                   bp.get("S_op", "<="), bp.get("R_op", ">="))
                 for lo, hi, li, hi_i in zip(d["lo"], d["hi"],
                                             d["lo_inc"], d["hi_inc"])]
    vc = d["call"].value_counts()
    print("\n  interpretation:")
    for k in ("S", "I", "R", "ambiguous"):
        print(f"    {k:<10}{int(vc.get(k,0)):>7,}")

    binary = d[d["call"].isin(["S", "R"])].copy()
    print(f"\n  BINARY analysis set (S or R only): {len(binary):,}")
    print(f"    excluded: {int(vc.get('I',0)):,} intermediate, "
          f"{int(vc.get('ambiguous',0)):,} unresolvable")
    print("    NOTE: PPV/NPV/sensitivity/specificity below are computed on this")
    print("    binary set; intermediate and unresolvable isolates are excluded.")

    # ---------- 6. discordance ----------
    pos = binary[binary["carb_pos"]]; neg = binary[~binary["carb_pos"]]
    fs = int((pos["call"] == "S").sum()); fr = int((neg["call"] == "R").sum())
    p1, lo1, hi1 = wilson(fs, len(pos)); p2, lo2, hi2 = wilson(fr, len(neg))
    print("\n" + "=" * 78)
    print("DISCORDANCE")
    print("=" * 78)
    print(f"carbapenemase-positive : n = {len(pos):,}")
    print(f"   phenotypically susceptible : {fs:,}  ({p1:.1f}%, 95% CI {lo1:.1f}-{hi1:.1f})")
    print(f"carbapenemase-negative : n = {len(neg):,}")
    print(f"   phenotypically resistant   : {fr:,}  ({p2:.1f}%, 95% CI {lo2:.1f}-{hi2:.1f})")

    tp = int((pos["call"] == "R").sum()); tn = int((neg["call"] == "S").sum())
    denom = lambda x: x if x else np.nan
    print(f"\n  contingency (binary set, total {tp+fs+fr+tn:,}):")
    print(f"    gene+/R {tp:>6,}   gene+/S {fs:>6,}")
    print(f"    gene-/R {fr:>6,}   gene-/S {tn:>6,}")
    print(f"  PPV {tp/denom(tp+fs):.3f}  NPV {tn/denom(tn+fr):.3f}  "
          f"sens {tp/denom(tp+fr):.3f}  spec {tn/denom(tn+fs):.3f}")

    # ---------- 7. by family ----------
    print("\n" + "=" * 78)
    print("DISCORDANCE BY CARBAPENEMASE FAMILY")
    print("=" * 78)
    rows = []
    for fam, g in pos.groupby("carb_family"):
        if len(g) < a.min_n:
            continue
        k = int((g["call"] == "S").sum()); p, lo, hi = wilson(k, len(g))
        rows.append(dict(family=fam, n=len(g), n_susceptible=k,
                         pct=round(p, 1), ci_lo=round(lo, 1), ci_hi=round(hi, 1)))
    fam_tab = pd.DataFrame(rows).sort_values("pct", ascending=False)
    print(fam_tab.to_string(index=False) if len(fam_tab) else "  (no family reaches min-n)")

    # ---------- 8. porin within family, explicit 2x2 ----------
    print("\n" + "=" * 78)
    print("PORIN CLASS WITHIN FAMILY")
    print("=" * 78)
    rows = []
    for fam in fam_tab["family"] if len(fam_tab) else []:
        sub = pos[pos["carb_family"] == fam]
        for pr in PORIN_ORDER:
            g = sub[sub["porin"] == pr]
            if len(g) < a.min_n:
                continue
            k = int((g["call"] == "S").sum()); p, lo, hi = wilson(k, len(g))
            rows.append(dict(family=fam, porin=pr, label=PORIN_LABEL[pr],
                             n=len(g), n_susc=k, pct=round(p, 1),
                             ci_lo=round(lo, 1), ci_hi=round(hi, 1)))
    mech = pd.DataFrame(rows)
    print(mech.to_string(index=False) if len(mech) else "  (insufficient data)")

    if len(mech):
        print("\n  Fisher exact tests, intact vs OmpK36-disrupted (2x2 built explicitly:")
        print("  rows = [intact, disrupted], cols = [resistant, susceptible];")
        print("  OR < 1 means disruption reduces the odds of susceptibility):")
        ftab = []
        for fam in mech["family"].unique():
            sub = pos[pos["carb_family"] == fam]
            a11 = int(((sub["porin"] == "none") & (sub["call"] == "R")).sum())
            a12 = int(((sub["porin"] == "none") & (sub["call"] == "S")).sum())
            a21 = int((sub["porin_disrupted"] & (sub["call"] == "R")).sum())
            a22 = int((sub["porin_disrupted"] & (sub["call"] == "S")).sum())
            if min(a11 + a12, a21 + a22) < a.min_n:
                continue
            table = [[a11, a12], [a21, a22]]
            orr, pv = stats.fisher_exact(table)
            print(f"    {fam:<16} [[{a11},{a12}],[{a21},{a22}]]  OR = {orr:.3f}  p = {pv:.3g}")
            ftab.append(dict(family=fam, R_intact=a11, S_intact=a12,
                             R_disrupted=a21, S_disrupted=a22,
                             odds_ratio=orr, p_value=pv))
        if ftab:
            ft = pd.DataFrame(ftab)
            # BH across the family of tests actually performed here
            p_sorted = np.sort(ft["p_value"].values)
            order = np.argsort(ft["p_value"].values)
            n_t = len(ft)
            q = np.minimum.accumulate((p_sorted * n_t / (np.arange(n_t) + 1))[::-1])[::-1]
            qq = np.empty(n_t); qq[order] = np.clip(q, 0, 1)
            ft["q_BH"] = qq
            ft.to_csv(OUTDIR / f"recordlevel_fisher_{a.drug}{a.tag}.tsv",
                      sep="\t", index=False)
            print(f"\n  BH-adjusted q-values written to "
                  f"{OUTDIR}/recordlevel_fisher_{a.drug}{a.tag}.tsv")

    # ---------- 9. outputs ----------
    # ---- stage audit: Figure 1 is built from this, never from constants ----
    audit = [
        ("phenotype records for this drug", n_all),
        ("records with a numeric value (mm and computational excluded)", len(r0)),
        (f"records interpreted against {a.standard or 'any standard'}", n_after_std),
        (f"records generated by {a.method or 'any method'}", len(r)),
        ("genomes with >=1 usable record", n_genomes_with_record),
        ("reconciled by interval intersection", len(ph)),
        ("irreconcilable records (excluded)", len(cf)),
        ("Kleborate genomes", n_kb),
        ("confirmed K. pneumoniae", n_kb_kp),
        ("genotyping failures", 7337 - n_kb if n_kb < 7337 else 0),
        ("genomes with linked genotype", len(d)),
        ("susceptible", int((d["call"] == "S").sum())),
        ("intermediate", int((d["call"] == "I").sum())),
        ("resistant", int((d["call"] == "R").sum())),
        ("unresolvable", int((d["call"] == "ambiguous").sum())),
        ("binary analysis set", int(d["call"].isin(["S", "R"]).sum())),
    ]
    pd.DataFrame(audit, columns=["stage", "n"]).to_csv(
        OUTDIR / f"recordlevel_audit_{a.drug}{a.tag}.tsv", sep="\t", index=False)

    keep = ["genome_id", "ST", "carb_pos", "carb_family", "carb_allele", "porin",
            "porin_disrupted", "esbl", "lo", "hi", "lo_inc", "hi_inc",
            "n_records", "method",
            "standard", "platform", "year", "call"]
    d[[c for c in keep if c in d.columns]].to_csv(
        OUTDIR / f"recordlevel_discordance_{a.drug}{a.tag}.tsv", sep="\t", index=False)
    if len(fam_tab):
        fam_tab.to_csv(OUTDIR / f"recordlevel_by_family_{a.drug}{a.tag}.tsv",
                       sep="\t", index=False)
    if len(mech):
        mech.to_csv(OUTDIR / f"recordlevel_mechanism_{a.drug}{a.tag}.tsv",
                    sep="\t", index=False)
    if len(cf):
        cf.to_csv(OUTDIR / f"recordlevel_conflicts_{a.drug}{a.tag}.tsv",
                  sep="\t", index=False)
    print(f"\n[out] {OUTDIR}/recordlevel_*_{a.drug}{a.tag}.tsv")

    print("\n" + "=" * 78)
    print("PROVENANCE OF THE ANALYSED RECORDS (record-level, post-filter)")
    print("=" * 78)
    for c in ("method", "standard", "platform", "year"):
        if c in d.columns and d[c].replace("", np.nan).notna().any():
            vc2 = d[c].replace("", "<not reported>").value_counts().head(6)
            print(f"  {c}: " + ", ".join(f"{k} ({v:,})" for k, v in vc2.items()))


if __name__ == "__main__":
    main()
